version: 2
updates:
- package-ecosystem: swift
  directory: "/WhiskyKit/"
  schedule:
    interval: daily
- package-ecosystem: swift
  directory: "/Whisky.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/"
  schedule:
    interval: daily
